# EasyBot Service Configuration
service:
  # 请参考EasyBot主程序日志输出的地址
  url: "ws://127.0.0.1:26990/bridge"
  # 身份标识,请在服务器生成
  token: ""
  # 忽略错误
  # 通常情况下 插件无法连接到EasyBot软件时会禁止所有玩家登陆游戏
  # 忽略错误后,玩家可以正常登陆且不进行任何检查(就算服务器处于强制绑定)
  ignore_error: false
  # 是否在服务端接收插件更新推送
  update_notify: true

# 命令设置
command:
  # 允许在此服务器进行绑定
  allow_bind: true

# 消息设置
message:
  # 玩家使用命令开始绑定
  bind_start: |
    §f[§a!§f] 开始绑定,请在群 §e123456 §f输入 '绑定 #code' 进行绑定!
    §f[§c!§f] 请在§a #time §f前完成验证,到时将自动取消绑定!
  bind_success: "§f[§a!§f] 绑定§f §a#account §f(§a#name§f) 成功!"
  bind_fail: "§f[§c!§f] §c绑定失败 #why"
  sync_success: "§f[§a!§f] §f发送成功!"

event:
  # 玩家绑定成功
  # 玩家绑定成功后可以执行命令,以控制台身份执行
  # 可以使用 $player 获取绑定成功的玩家名
  # 可以使用 $account 获取绑定成功的玩家账号 (如:QQ号)
  # 可以使用 $name 获取玩家绑定的账号名(如:QQ名称)
  enable_success_event: false # 如果要在玩家绑定成功时执行命令,请启用此选项
  bind_success:
    - "say $player 绑定成功! QQ: $account 昵称: $name"

# 调试模式,返回BUG时请将此选项设置为true,然后复现BUG操作再将日志给群主
debug: false